### ISSUE TITLE
关于头文件的引入问题

### ISSUE THREAD

**Issue by zzxT** [chronolaw/ngx_ansic_dev#1]
老师，你好：
       我最近在阅读Nginx完全开发指南这本书。我是一个Java程序员，对cpp和c，只有大学时期的一点皮毛水平，然后我遇到一个问题。我在开发第一个hello_http_demo时候，我发现在书中和github上的代码都只是引入了nginx的几个头文件。我如果只是这么做，在我本地会找不到很多宏，和函数定义。
我需要添加以下三个头文件才不会报错 #include <stddef.h> #include <MacTypes.h>  #include <stdio.h> 。 是我哪里的配置有问题吗？

**Comment by chronolaw** [comment]
不好意思，才看到你的问题。
这些代码都是经过编译验证的，nginx的头文件已经包含了所有需要的头文件，所有不需要额外包含。
如果还有问题，建议贴出提示信息。

**Comment by zzxT** [comment]
老师，你好：
头文件的问题，我搞清楚了。那些头文件在nginx的源码中是都存在的，只要引入你书中写到的就可以了。我按照书中说的编译运行都可以。遇到的困惑就是在clion中开发的时候，因为clion的开发环境中没有引入ngxin的头文件，所以会飘红。想问问老师平时常用什么IDE或者编辑器开发c语言的项目。

我在mac下面编译遇到一个问题，我解决了在这里写一下希望能帮助到其他人。
环境是mac下，编译1.6.0版本。如果用brew安装最新的openssl，安装后的路径可能会是这样的
/usr/local/opt/openssl@1.1/bin/openssl
编译ngxin我们会这么写：
./configure   --with-openssl=/usr/local/opt/openssl@1.1 --with-http_ssl_module
然后执行 make命令会报错：
```
cd /usr/local/opt/openssl@1.1 \
	&& if [ -f Makefile ]; then /Library/Developer/CommandLineTools/usr/bin/make clean; fi \
	&& ./config --prefix=/usr/local/opt/openssl@1.1/.openssl no-shared no-threads  \
	&& /Library/Developer/CommandLineTools/usr/bin/make \
	&& /Library/Developer/CommandLineTools/usr/bin/make install_sw LIBDIR=lib
/bin/sh: ./config: No such file or directory
make[1]: *** 
```
两个问题
1.  目录/usr/local/opt/openssl@1.1/.openssl  是没有.openssl的。我是自己手动创建的，然后把include目录和lib目录复制进去
2. 第二个问题是 上面那个报错的命令是在Makefile里面，然后找到那个位置 他的上一行
/usr/local/opt/openssl@1.1/.openssl/include/openssl/ssl.h: 
改成
/usr/local/opt/openssl\@1.1/.openssl/include/openssl/ssl.h:

我也不知道为什么这样就可以😭

**Comment by chronolaw** [comment]
我一般在Linux下用vim写代码，也不安装什么插件，就用常见的那些快捷键。

IDE集成环境很多年没用了，可能跟不上时代，不了解现在的这些工具，设置起来比较麻烦，没有Makefile那么简单方便。

Mac的环境搭建还是比Linux麻烦一些，资料也比较少，抱歉帮不上你。

**Comment by zzxT** [comment]
还是感谢老师抽空解答我的问题。我也在向用编辑器开发，自己直接用编译构建工具进化～
我还买了老师的HTTP协议极客专栏，学习到了知识，而且感觉涨了见识😊，谢谢老师出的专栏。

**Comment by chronolaw** [comment]
以后考虑还会讲一下C++开发，还望捧场，笑。
